### ISSUE TITLE
Write failed: ENOSPC (No space left on device)

### ISSUE THREAD

**Issue by flamyoad** [flamyoad/Honnoki#18]
```
Caused by android.system.ErrnoException: write failed: ENOSPC (No space left on device)
       at libcore.io.Linux.writeBytes(Linux.java)
       at libcore.io.Linux.write(Linux.java:288)
       at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
       at libcore.io.IoBridge.write(IoBridge.java:553)
       at java.io.FileOutputStream.write(FileOutputStream.java:326)
       at kotlin.io.ByteStreamsKt.copyTo(ByteStreamsKt.java:5)
       at com.flamyoad.honnoki.cache.CoverCache.write(CoverCache.java:5)
       at com.flamyoad.honnoki.cache.CacheManager$getCoverImage$2.invoke(CacheManager.java:5)
       at com.flamyoad.honnoki.cache.CacheManager$getCoverImage$2.invoke(CacheManager.java:5)
       at com.flamyoad.honnoki.utils.extensions.GlideExtensionsKt$downloadIntoFile$1.onResourceReady(GlideExtensionsKt.java:1)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:2)
       at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:4)
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:9)
       at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:9)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6892)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
```

```
Device
Brand:vivo
Model:vivo 1908
Orientation: Portrait
RAM free: 567.54 MB
Disk free: 98.12 MB
```

```
Operating System
Version:8.1.0
Orientation: Portrait
Rooted:No
```

```
Crash
Date:Aug 12, 2021, 9:08:50 PM
App version:1.0.2 (3)
```

**Comment by flamyoad** [comment]
https://github.com/flamyoad/Honnoki/blob/4537779df5ae2e004228bd5a504b6716dbfaf8e5/app/src/main/java/com/flamyoad/honnoki/cache/CoverCache.kt#L31-L40

Add exception handling for `IOException` or `ErrnoException` in this method
